### ISSUE TITLE
[question] why shd I use this instead of django-webpack-loader

### ISSUE THREAD

**Issue by simkimsia** [AccordBox/python-webpack-boilerplate#15]
Sorry I am curious

But as a django dev why is this better or more suited for me if I want to use webpack in my dockerized django project compared with django-webpack-loader?

**Comment by michael-yin** [comment]
@simkimsia 

When using `django-webpack-loader`, you need to create Webpack project on your own, which is not easy for many newbie Django developers.

`python-webpack-boilerplate` can let you play with modern frontend tech in Django, even you have no idea how to config Webpack.

Thx.

**Comment by simkimsia** [comment]
Thx for clarifying. You should put that front and early in the readme.
