### ISSUE TITLE
`Webpack` Error During `Tailwind` Configuration 

### ISSUE THREAD

**Issue by FilipWozniak** [AccordBox/python-webpack-boilerplate#38]
I believe it's related to #36, and I think the issue left unresolved.

I get exactly the same error message as @Ladet02.

I've installed `Wagtail` with "`npm` command at `frontend` directory" setup, enabled live reloading feature and I get the following error trying to configure `Tailwind`:

![image](https://user-images.githubusercontent.com/64541581/219471458-795f57f8-662a-4530-9aa1-893ff8181d49.png)

![image](https://user-images.githubusercontent.com/64541581/219471536-df3930dc-ceda-40a8-ae4c-fef938218f22.png)

I've checked all the steps provided [here](https://python-webpack-boilerplate.readthedocs.io/en/latest/setup_with_tailwind/) like a million times.

**Comment by michael-yin** [comment]
@FilipWozniak 

If possible, could you please create a project and upload your code to Github

I can not figure out the problem from the above screenshot.

Thx.

**Comment by FilipWozniak** [comment]
> If possible, could you please create a project and upload your code to Github

Sure, here it is.

[https://github.com/FilipWozniak/dj-fw_blog](https://github.com/FilipWozniak/dj-fw_blog)

**Comment by michael-yin** [comment]
@FilipWozniak 

You can try to put `tailwind.config.js` at the root directory, jus like this https://github.com/AccordBox/wagtail-tailwind-blog

Thx.

**Comment by FilipWozniak** [comment]
Thank you, it worked! I apologize for unnecessarily bothering you, but the "Python Webpack Boilerplate" website did not specify anywhere that `tailwind.config.js` must be in the `root` directory, and it was generated by default in the `frontend` folder. I should have thought of that 😉

<img width="797" alt="image" src="https://user-images.githubusercontent.com/64541581/222067375-277fa9ff-83e3-4280-a923-69d2c3081917.png">
